const condition = () => ({
  pain: 3,
  isBleeding: false,
  isBroken: false,
});

export const body = {
  head: {
    eye: { side: {} },
    nose: {},
    mouth: {},
    ear: { side: {} },
  },
  arm: {
    side: {
      which: {},
      shoulder: {},
      upper: {},
      elbow: {},
      forearm: {},
      wrist: {},
      hand: {
        finger: {
          which: {}, // index|middle|ring|pinky
        },
        thumb: {},
        palm: {},
      },
    },
  },
  torso: {
    chest: {},
    abdomen: {},
  },
  groin: {},
  leg: {
    side: {
      which: {},
      thigh: {},
      knee: {},
      lowerLeg: {},
      ankle: {},
      foot: {
        toe: {
          which: {},
        },
        heel: {},
      },
    },
  },
};

export const bodyParts = [
  "leftEye",
  "rightEye",
  "mouth",
  "nose",
  "leftEar",
  "rightEar",
  "neck",
  "leftChest",
  "rightChest",
  "abdomen",
  "groin",
  "leftGlute",
  "rightGlute",
  "leftThigh",
  "leftKnee",
  "leftShin",
  "leftAnkle",
  "leftFoot",
  "rightThigh",
  "rightKnee",
  "rightShin",
  "rightAnkle",
  "rightFoot",
  "leftShoulder",
  "leftUpperArm",
  "leftElbow",
  "leftForearm",
  "leftWrist",
  "leftHand",
  "leftThumb",
  "leftIndexFinger",
  "leftMiddleFinger",
  "leftRingFinger",
  "leftPinkyFinger",
  "leftPalm",
  "rightShoulder",
  "rightUpperArm",
  "rightElbow",
  "rightForearm",
  "rightWrist",
  "rightHand",
  "rightThumb",
  "rightIndexFinger",
  "rightMiddleFinger",
  "rightRingFinger",
  "rightPinkyFinger",
  "rightPalm",
];
