export const users = [
  {
    uuid: "19a2bee38879d41e962",
    name: "Oscar Davidson",
    age: 92,
    gender: "non-binary",
    email: "oscar-davidson@gmail.org",
    phone: "(263) 834-2498",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "17 Roosevelt Lake",
  },
  {
    uuid: "19a2bee388787d049c5",
    name: "Umar Young",
    age: 20,
    gender: "non-binary",
    email: "umar-young@gmail.org",
    phone: "(227) 857-4533",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "Madison Glade",
  },
  {
    uuid: "19a2bee38871c4bc8e01",
    name: "Adam Hardison",
    age: 52,
    gender: "male",
    email: "adamhardison@gmail.com",
    phone: "(759) 565-8753",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "Adams Blvd",
  },
  {
    uuid: "19a2bee3887c170b47d",
    name: "Queen Ziegler",
    age: 94,
    gender: "female",
    email: "queen_ziegler@gmail.net",
    phone: "(324) 538-8925",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "18 McKinley Mills",
  },
  {
    uuid: "19a2bee3887f406985d",
    name: "Zelda Vickers",
    age: 51,
    gender: "female",
    email: "zelda_vickers@gmail.net",
    phone: "(409) 407-2925",
    wasUnconscious: false,
    isVictim: true,
    injuries: {},
    location: "Coolidge Glade",
  },
  {
    uuid: "19a2bee38871a772a885",
    name: "Jason Johnson",
    age: 87,
    gender: "male",
    email: "jasonjohnson@gmail.com",
    phone: "(710) 427-6613",
    wasUnconscious: false,
    isVictim: true,
    injuries: {},
    location: "18 McKinley Mills",
  },
  {
    uuid: "19a2bee38874247dbb1",
    name: "Oscar Xiao",
    age: 40,
    gender: "non-binary",
    email: "oscar-xiao@gmail.org",
    phone: "(111) 200-5553",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "Adams Blvd",
  },
  {
    uuid: "19a2bee3887adb920aa",
    name: "Whitney Isley",
    age: 48,
    gender: "female",
    email: "whitney_isley@gmail.net",
    phone: "(291) 459-0890",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "Madison Glade",
  },
  {
    uuid: "19a2bee3887b8f8f203",
    name: "Queen Young",
    age: 16,
    gender: "female",
    email: "queen_young@gmail.net",
    phone: "(310) 332-2627",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "Coolidge Glade",
  },
  {
    uuid: "19a2bee388721f63f59a",
    name: "Queen Preston",
    age: 42,
    gender: "female",
    email: "queen_preston@gmail.net",
    phone: "(911) 657-9226",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "Johnson Drive",
  },
  {
    uuid: "19a2bee3887141b9d5f0",
    name: "Queen Graham",
    age: 42,
    gender: "female",
    email: "queen_graham@gmail.net",
    phone: "(539) 766-5264",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "Madison Glade",
  },
  {
    uuid: "19a2bee388717d39562a",
    name: "Whitney Xiao",
    age: 74,
    gender: "female",
    email: "whitney_xiao@gmail.net",
    phone: "(639) 587-6906",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "19 Jackson Parkway",
  },
  {
    uuid: "19a2bee388713acd272b",
    name: "Frank Eeastley",
    age: 83,
    gender: "non-binary",
    email: "frank-eeastley@gmail.org",
    phone: "(528) 149-0731",
    wasUnconscious: false,
    isVictim: true,
    injuries: {},
    location: "Adams Blvd",
  },
  {
    uuid: "19a2bee388710ce43ef0",
    name: "Roger Fox",
    age: 17,
    gender: "non-binary",
    email: "roger-fox@gmail.org",
    phone: "(451) 125-2208",
    wasUnconscious: false,
    isVictim: true,
    injuries: {},
    location: "Adams Blvd",
  },
  {
    uuid: "19a2bee38876f5be0e1",
    name: "Peter Johnson",
    age: 41,
    gender: "male",
    email: "peterjohnson@gmail.com",
    phone: "(186) 829-2321",
    wasUnconscious: false,
    isVictim: true,
    injuries: {},
    location: "Eisenhower Road",
  },
  {
    uuid: "19a2bee38871339b15e9",
    name: "Xavier Underwood",
    age: 49,
    gender: "non-binary",
    email: "xavier-underwood@gmail.org",
    phone: "(516) 076-9001",
    wasUnconscious: false,
    isVictim: true,
    injuries: {},
    location: "13 Cleveland Lake",
  },
  {
    uuid: "19a2bee38877c2f4ac2",
    name: "Yuri Mangrove",
    age: 50,
    gender: "male",
    email: "yurimangrove@gmail.com",
    phone: "(208) 347-4114",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "18 McKinley Mills",
  },
  {
    uuid: "19a2bee38878f5b6ebd",
    name: "Zelda Hardison",
    age: 77,
    gender: "female",
    email: "zelda_hardison@gmail.net",
    phone: "(240) 513-4013",
    wasUnconscious: false,
    isVictim: true,
    injuries: {},
    location: "Madison Glade",
  },
  {
    uuid: "19a2bee3887142561bfc",
    name: "Oscar Underwood",
    age: 40,
    gender: "non-binary",
    email: "oscar-underwood@gmail.org",
    phone: "(540) 790-6812",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "17 Roosevelt Lake",
  },
  {
    uuid: "19a2bee388715e86c7ce",
    name: "Whitney Vickers",
    age: 74,
    gender: "female",
    email: "whitney_vickers@gmail.net",
    phone: "(588) 085-8574",
    wasUnconscious: true,
    isVictim: true,
    injuries: {},
    location: "11 Ford Ave",
  },
];
