import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const phosphateSolid = localFont({
  src: "../../public/assets/fonts/PhosphateSolid.ttf",
  variable: "--font-phosphate",
});

export const metadata: Metadata = {
  title: "Recover",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${phosphateSolid.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
