import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "@/components/layout/Footer";

const phosphateSolid = localFont({
  src: "../../public/assets/fonts/PhosphateRR Solid.ttf",
  variable: "--font-phosphate",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const monty = Montserrat({
  subsets: ["latin"],
  variable: "--font-monty",
});

export const metadata: Metadata = {
  title: "Recover",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${phosphateSolid.variable} ${inter.variable} ${monty.variable} antialiased h-screen flex flex-col`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
